### ISSUE TITLE
Failed to execute tests with voting authorities

### ISSUE THREAD

**Issue by sc0Vu** [katzenpost/catshadow#29]
Hi

Thanks for the great work.

Recently, I try to execute the catshadow test with local docker network for voting authority.

The local network worked great! But when I execute test, I saw this error:

```
 $ GORACE=history_size=7 go test -tags=docker_test -race -v -run Docker
=== RUN   TestDockerPandaSuccess
19:22:49.304 DEBU pki/voting/Client: Get(ctx, 100834)
--- FAIL: TestDockerPandaSuccess (0.02s)
panic: pki: requested epoch will never get a document [recovered]
	panic: pki: requested epoch will never get a document

goroutine 35 [running]:
testing.tRunner.func1.1(0x1b301a0, 0xc00011a8c0)
	/usr/local/Cellar/go/1.15.8/libexec/src/testing/testing.go:1072 +0x46a
testing.tRunner.func1(0xc00029e180)
	/usr/local/Cellar/go/1.15.8/libexec/src/testing/testing.go:1075 +0x636
panic(0x1b301a0, 0xc00011a8c0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:975 +0x47a
github.com/katzenpost/client.AutoRegisterRandomClient(0xc00021c690, 0x0, 0x0)
	~/go/pkg/mod/github.com/katzenpost/client@v0.0.22/client.go:62 +0x13e7
github.com/katzenpost/catshadow.createCatshadowClientWithState(0xc00029e180, 0xc00028c380, 0x65, 0x109ae00, 0x10b58e0)
	~/Desktop/projects/hashcloak/catshadow/client_docker_test.go:66 +0x1ac
github.com/katzenpost/catshadow.TestDockerPandaSuccess(0xc00029e180)
	~/Desktop/projects/hashcloak/catshadow/client_docker_test.go:130 +0x8f
testing.tRunner(0xc00029e180, 0x1c34478)
	/usr/local/Cellar/go/1.15.8/libexec/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.8/libexec/src/testing/testing.go:1168 +0x5bc
exit status 2
FAIL	github.com/katzenpost/catshadow	0.245s
```

Did I set something wrong in client?

Thanks

**Comment by mixmasala** [comment]
Sorry I didn't see this issue before now - you need to wait for the voting authorities to bootstrap and reach consensus - the error 	"panic: pki: requested epoch will never get a document" is because the authorities cannot vote for the current epoch and will start the voting process either within the current epoch (for next epoch) if it isn't yet too late to begin a vote, or they will wait until the end of the current epoch to start the voting round.

The current default epoch duration is 20 minutes, so you may need to wait 40 minutes for the authorities to have bootstrapped (worst case scenario)...

for testing, however, you can use the build flag "WarpedEpoch" which will decrease this period to 2 minutes. You'll need to pass this build flag to each of the authority and server images as well as the client test. Hope this helps!
